### ISSUE TITLE
Auctions: showing which language tab realm is on

### ISSUE THREAD

**Issue by shifuren** [ThingEngineering/wowthing-again#1119]
When buying tons of missing items, often there is need to relog to dozens of different servers for those cheapest ones, and its quite hard to remember on which language tab which realm is. Some realm language indicator near realm name would help to save a lot of time :)
(maybe instead of that region indicator in front, since probably no one searches through multiple regions at once, trading is only region-wide)

![изображение](https://github.com/ThingEngineering/wowthing-again/assets/15345491/6772fd03-44de-4c93-a1ef-4acd8d657f55)

**Comment by madcowfred** [comment]
I added this at some point, woops.
