### ISSUE TITLE
New level requirements from ~10.1.7 aren't considered for Timewalking tasks

### ISSUE THREAD

**Issue by RiightX** [ThingEngineering/wowthing-again#1185]
Hello wonderful friends who have made such a fantastic tool!

I was setting up some tabs to check who all I've done the Timewalking weekly on (the item drop from completing the dungeon, not the weekly from the Valdrakken NPC), and I noticed that even though the [requirements](https://us.battle.net/support/en/article/137975) were changed at some point, WoWthing seems to be not considering characters under 60 (the old level requirement for most of Dragonflight) eligible to get the quest for the badges.

For example, here is my screenshot from today of my WoWthing page I have set up filtering for characters level 30 and above, who are eligible to queue for Timewalking and get the Unstable Prism:
![image](https://github.com/ThingEngineering/wowthing-again/assets/82491290/522ec671-50b9-4182-a727-7a9c16f6bf38)

The "TW" column for the quest The Unstable Prism is only populated for characters 60 and above. I have tried looking through the repo to see where this might be calculated, but my small sysadmin-only brain can't seem to find it. 🙂

**Comment by madcowfred** [comment]
This should (finally) actually be fixed now
