### ISSUE TITLE
Upgrade tracks do not match the crests that need to be used

### ISSUE THREAD

**Issue by strchsr** [ThingEngineering/wowthing-again#1196]
On the /items/equipped page, if "Upgradeable" is enabled, the crests needed to upgrade an item shown are a tier lower than they are supposed to be for a specific breakpoint. For example, it says that you can use Wyrm crests to upgrade a 476 item, where you actually need Aspect crests to upgrade past 476 to 480/483/486/489, as Wyrm crests can only be used up to 476.

**Comment by madcowfred** [comment]
It takes that into account, you still need to use Wyrms to upgrade the items to 4/6 in the first place. That's why they all have two types of crest.

![image](https://github.com/ThingEngineering/wowthing-again/assets/99630/926e2dc4-01bd-4196-8f23-a0e06275664f)

**Comment by strchsr** [comment]
I was looking at this, specifically
![ss+(2024-01-24+at+11 06 44)](https://github.com/ThingEngineering/wowthing-again/assets/83755446/1f0c56e2-e5bc-46f7-b7cb-ed9fe0fb33bb)

**Comment by madcowfred** [comment]
Oops, wrong thing, sorry. It looks like they're off by 1 upgrade step - 476 shows wyrm instead of aspect, 480 shows aspect as it should? Weird. I'll try to get a fix in later today.

**Comment by strchsr** [comment]
I was trying to figure out how to word it without it being confusing, since most of my gear needs Wyrms or Aspects to upgrade, so I haven't seen if it has the same issue with say, Whelpling and Drake crests.
