### ISSUE TITLE
How did this find characters I deleted a long time ago?

### ISSUE THREAD

**Issue by Alfakennyone** [ThingEngineering/wowthing-again#1207]
![image](https://github.com/ThingEngineering/wowthing-again/assets/61605997/656cae7a-5281-45df-8355-04ab10885d39)

These were characters used on a referral account back during the Legion pre-launch event and used as leveling boosts for my main account. They were obviously not level 10s because WoD was 100

Some of them you can search on www.warcraft.com and it'll say View All 1 Results but when you click it, it shows nothing.

When I go to Settings on Wowthing.org website, I can identify my Wow#1 - main, Wow#4 - referral acc, Wow#5 - referral acc, Wow#7 8 9 - Starter accounts (these are newer) and each have their own IDs

The characters in question are by themselves with a different ID than the others.

So how? Or is this a bug/thing on blizzard's ends keeping permanently deleted character data (even though I checked on every account just to make sure they can't be restored, there is none to be restored)?

**Comment by SisrenWarrior** [comment]
Its possible its picking up lingering character files/folders in the account section of your WoW install. Not a definitive answer, just a guess.

**Comment by Alfakennyone** [comment]
> Its possible its picking up lingering character files/folders in the account section of your WoW install. Not a definitive answer, just a guess.

Decent guess but I never uploaded any data by using the add-on and there's no character data in my WOW install

Just weird, it's only these characters and not any other ones I've deleted

**Comment by madcowfred** [comment]
@Alfakennyone absolutely no idea. WoWthing uses the official Blizzard "give me a list of accounts and characters" API to get that information, and that's it as far as picking up characters go :\
