### ISSUE TITLE
Battlenet login results in 403s on Blizzard's side, or 500s on wowthing's side.

### ISSUE THREAD

**Issue by bhaberer** [ThingEngineering/wowthing-again#1209]
Encountering an issue where I see the following two issues: 

- Battlenet 403s
  1. Nav to wowthing
  2. Click Login via bnet 
  3. Log in via bnet and allow via 2fa 
  4. battle.net displays white page with 403 error
 
I think the above *might* be related to my vpn, but unsure. It stopped happening when I disconnected it, but I couldn't get it to start happening again with cleared cookies and reconnected to my vpn. 

The bigger issue is that if I log into battlenet and then click the login link on wowthing I see the following: 
![image](https://github.com/ThingEngineering/wowthing-again/assets/49709/41c5cde4-9da8-44c8-aeff-efd11f9dfb08)

Not sure what info is helpful for debugging, feel free to contact.

**Comment by SisrenWarrior** [comment]
Same issue. B.net is pretty much always connected. WoWThing giving a 404 error whenever clicking on log in.

**Comment by bhaberer** [comment]
@SisrenWarrior Checked with the dev discord, they've been fighting with blizzard's apis for a while, so it'll be fixed in a bit, but it's an ongoing headache.
