### ISSUE TITLE
heroic dungeons showing up as 506 for dungeon vault

### ISSUE THREAD

**Issue by ahlswede** [ThingEngineering/wowthing-again#1220]
heroic dungeons showing up as 506 for dungeon vault for homepage, they should be 489. happy to provide more details if this isn't enough information.

wowthingy:
![wowthing-dungeon-vault](https://github.com/ThingEngineering/wowthing-again/assets/1529828/3275138c-7f22-4402-8a45-f2cf5f98ed8f)

in game:
![ingame-dungeons](https://github.com/ThingEngineering/wowthing-again/assets/1529828/02effbc9-2173-49e0-a4c6-3a72d8a4c56a)

thank you!

**Comment by madcowfred** [comment]
This should actually be fixed now.
