### ISSUE TITLE
Heroic ToT Plate Sets - Missing items that are completed

### ISSUE THREAD

**Issue by Lucetia** [ThingEngineering/wowthing-again#1252]
It looks like the Death Knight, Paladin, and Warrior sets aren't registering some of the pieces even though in-game it shows that you own them.  Originally using the ensembles it didn't flag these items, but seems a few days later it does.  Maybe Blizzard fixed it?

Death Knight - Battleplate of the All-Consuming Maw (Heroic Recolor)
- `Abandoned Zandalari Goreplate` - https://www.wowhead.com/item=96719/abandoned-zandalari-goreplate
- `Columnbreaker Stompers` - https://www.wowhead.com/item=96723/columnbreaker-stompers

Warrior - Battleplate of the Last Mogu (Heroic Recolor)
- `Abandoned Zandalari Bucklebreaker` - https://www.wowhead.com/item=96720/abandoned-zandalari-bucklebreaker

Paladin - Battlegear of the Lightning Emperor (Heroic Recolor)
- `Abandoned Zandalari Greatbelt` - https://www.wowhead.com/item=96718/abandoned-zandalari-greatbelt
- `Vaultwalker Sabatons` - https://www.wowhead.com/item=96712/vaultwalker-sabatons

**Comment by Lucetia** [comment]
Another set that seems to be affected by this.

Druid - Vestments of the Haunted Forest (Heroic Recolor
-  `Abandoned Zandalari Silentbelt` - https://www.wowhead.com/item=96714/abandoned-zandalari-silentbelt

Wowhead includes this in the set, so the site has it listed.  In-game rightlicking and viewing its sources does not.  But either way the ensemble does flag the item as collected as I see the flag in my system.  So either way it should be showing as completed.

**Comment by madcowfred** [comment]
This is fixed now, those transmog sets include items that aren't transmoggable (???) and wowthing wasn't taking that into consideration.
