### ISSUE TITLE
Periodic Issue With Auctions -> Missing Pets, Missing Toys

### ISSUE THREAD

**Issue by swotam** [ThingEngineering/wowthing-again#1320]
I've encountered a repetitive issue on wowthing.org with the Auctions -> Missing Pets and Auctions -> Missing Toys sections.

For Auctions -> Missing Pets the section will often fail to load and instead displays "No Results!" regardless of which display options are chosen. The issue is present across multiple browsers and devices and does not appear to be impacted by ad blockers or similar tools. This issue will persist for hours / days before seemingly resolving itself and starting to work again. No user action appears to affect this behaviour, it either works or it does not until it starts working again.

For Auctions -> Missing Toys the section fails to load and displays "No Results!" if the **All Realms** options is enabled. Disabling this option will show results as expected. This behaviour seems consistent and does not change as far as I can tell. The issue is present across multiple browsers and devices and does not appear to be impacted by ad blockers or similar tools. 

When experiencing these issues the other sections under Auctions load data correctly and display results as expected, so the issue seems to be limited to the Missing Pets and Missing Toys section.

Any assistance investigating this issue would be appreciated.

**Comment by madcowfred** [comment]
I think we tracked down the weirdness going on here, if not drop by the Discord and I can check logs/etc
