### ISSUE TITLE
Items -> Equipped "Highlight Item Level" appears to be broken

### ISSUE THREAD

**Issue by Sahasrahla** [ThingEngineering/wowthing-again#1342]
In the Items -> Equipped page, I can select the checkbox to highlight by item level, and it will fade every piece of equipment on the page, regardless of the number in the item level box or the item level of the pieces of gear. I believe this functionality broke around the time of TWW launch.

![image](https://github.com/user-attachments/assets/f5f7f7f5-9714-4732-9c11-f85280c2bcca)

**Comment by madcowfred** [comment]
Should be fixed, it was limiting that to max level for some reason

**Comment by Sahasrahla** [comment]
Confirmed it's fixed. Thanks!
