### ISSUE TITLE
[Event] World Quests has new quest ID for TWW

### ISSUE THREAD

**Issue by SoulCookie** [ThingEngineering/wowthing-again#1364]
The quest for the WQ weekly has changed in TWW; **it is now [83366](https://www.wowhead.com/quest=83366)**.

(Flagging this because I noticed my main's completion of the WQs wasn't reflected on the overview of characters.)

Thanks, and keep up the great work!

**Comment by madcowfred** [comment]
Oop, this was updated at the time
