### ISSUE TITLE
Ideas:Warbank gold and Great Vault

### ISSUE THREAD

**Issue by SunnyM-ha** [ThingEngineering/wowthing-again#1367]
Just a couple of ideas/suggestions if you have some time:

1. The gold display doesnt count Warbank gold, so it looks as tho I've lost 90% of my gold as I've been putting most of it from all my toons into the warbank so any of them can easily access it as needed - would be nice to include that in the total
2. Would be nice to show Great Vault progress, so you can easily see which toons have rewards waiting to be collected without having to go in game and relog to every alt

Thanks again for an awesome site! :)

**Comment by madcowfred** [comment]
2 is already done - go into Settings>Views>whatever, Home Columns, and drag "Vault - (Dungeons/Raid/World)" over to the left. 1 I'm slowly working on, honest.

**Comment by SunnyM-ha** [comment]
I added that view - thanks, works awesome :)
No rush on 1, I know a bunch of the addons also broke on that until the authors figured out how to access it - thanks again for your work on this awesome site :)

**Comment by madcowfred** [comment]
Warbank gold tracking added, needs addon v11.0.2.25+

**Comment by SunnyM-ha** [comment]
Awesome thanks, still see 11.0.2.24 on Curseforge so my addon manager hasnt pulled it yet - till try it tomorrow, thanks dude :)

**Comment by SunnyM-ha** [comment]
I just grabbed .25, can see the amount pulled into the website now at the top :)

Total on the character screen and the History graph dont include it yet tho

**Comment by madcowfred** [comment]
The total on the character screen won't include it because of grouping. History graph only generates data once an hour.

**Comment by SunnyM-ha** [comment]
Awesome, thanks again 😄
