### ISSUE TITLE
RFI: Char Specific Unlock Tracking

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#145]
Add a section that shows char specific unlocks - propose status' - locked/inprogress/fullyunlocked/done

Nazjatar (Start: A-56031 H-56030) (End: A-56156 H-55500)
Mechagon - Dependent upon completion of the Nazj "ends" (Start: A-57009 H-57024) (End: A-54088 H-55646)
Nzoth Assaults - Dependent upon completion of the Nazj "ends" (Start: A-58496 H-56030) (End: A-56156 H-58582)

Korthia Unlock (Unlocked / 3/9 completed (unlocks the last wq) / 9/9 COD line)

Molten Front
Isle of Thunder 
Timeless Isle

**Comment by madcowfred** [comment]
700 years later, added Molten Front/Isle of Thunder/Timeless Isle
