### ISSUE TITLE
RFI: Tracking of Additional Weekly Tasks

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#146]
For SL - current maw invasion complete, current tormentors of the week complete
For BFA - idk who gives a shit about this expansion man (i'd take lockouts i guess since i need to farm mounts)
Legion - WITHERED TRAINING PLEASE REMIND ME TO DO THIS T___T - Highlight if an emissary is up that you need a prestige reward from?

lock some of this shit behind premium status jfc let me patreon you

**Comment by madcowfred** [comment]
Added most of these, the emissary highlight stuff is kinda complicated and probably needs a separate tracking issue
