### ISSUE TITLE
RFI - Github/Readme

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#15]
https://gitlab.com/thing-engineering/wowthing/wowthing-again

Edit this page for the docker shit to say that its for setting up the dev environment cuz that's not clear and you link that page to normals, also do you actually want collaborators? write some stuff about what you're looking for if so

**Comment by madcowfred** [comment]
The new one, not sure if it's any better 😓 https://github.com/ThingEngineering/wowthing-again/blob/a6dc50bc4362b96287345c70dd840f38ac991ce9/README.md
