### ISSUE TITLE
Bug - Mixed pre/post-reset data

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#154]
I think this is the first actual bug I found. So I triggered a manual update because my wowthing uploader was stuck, and I got this! 
![image](https://user-images.githubusercontent.com/27977095/138172567-932eef73-8349-4c16-9058-f31b079e1e7b.png)

But only that first character's completion data is accurrate - or maybe my WoW2 account which is Bakatwa and Kyarebear, Kyansecrate and Kyarate are on my 2nd account, and they completed those items last week, but haven't touched this weeks.

**Comment by madcowfred** [comment]
This should be fixed at this point
