### ISSUE TITLE
Incomplete - Home (Table) - Keys UI

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#16]
![image](https://user-images.githubusercontent.com/27977095/121765543-8f13ea00-cb19-11eb-9c4e-8f4ca84522f5.png)

1. needs hover text explaining what it is
2. keystone favicon

**Comment by madcowfred** [comment]
Removed the icon, and the numbers have tooltips - if they don't work on mobile I'll have to work out a general fix for that :(
