### ISSUE TITLE
Bug special character names

### ISSUE THREAD

**Issue by R41z0r** [ThingEngineering/wowthing-again#165]
![78FC7C48-FEC5-428E-B442-F2DEDA6F3773](https://user-images.githubusercontent.com/6240199/138948477-c85908d7-7b1a-4a61-b8a8-cb37d7924fea.png)
Hey with special characters like the "Ð" the import from raider io isn't working, the rio is missing there.

**Comment by madcowfred** [comment]
Probably related to the Blizzard API bug with that same character, will look into it

**Comment by madcowfred** [comment]
Fixed
