### ISSUE TITLE
Upload Script For Mac

### ISSUE THREAD

**Issue by 4bitfocus** [ThingEngineering/wowthing-again#173]
Any chance for a python script uploader or a Mac version of the sync app? I can help with the former if you help with the details (mainly how to get around authenticating each time from the script).

**Comment by madcowfred** [comment]
There was a Python upload script for the old wowthing, but I have no idea where it is and I also have no Mac to test on. The upload process is pretttty simple:

- POST to https://www.wowthing.org/api/upload
- Body should be a UTF-8 JSON object:
`
{
  "apiKey": "apikeyhere",
  "luaFile": "WoWthing_Collector.lua file contents here"
}

It accepts `gzip` encoding to make the upload faster but it shouldn't be required.

**Comment by 4bitfocus** [comment]
Thanks! That worked! Even got it working with gzip. 😄
