### ISSUE TITLE
Newly created characters are missing

### ISSUE THREAD

**Issue by R41z0r** [ThingEngineering/wowthing-again#180]
Hey there,

newly created characters are missing on worthing.org - I created one two days ago, now 60 and it is not appearing on the website. In the .lua file he is there, I guess you only pull once the data from WoW Api and that's why it's missing?

`
["chars"] = {
		["EU/Antonidas/Rayzy"] = {
			["scanTimes"] = {
				["torghast"] = 1636787881,
				["lockouts"] = 1636787883,
				["bags"] = 1636787883,
				["pets"] = 1636787886,
				["toys"] = 1636717001,
				["vault"] = 1636787883,
				["mythicPlus"] = 1636787883,
				["mounts"] = 1636787886,
				["reputations"] = 1636787883,
				["quests"] = 1636787888,
				["transmog"] = 1636787888,
			},
			["lastSeen"] = 1636787895,
`

**Comment by madcowfred** [comment]
Log out and back in is the easiest way, can only check the API for character list within 24 hours of you logging in. I don't really want to trust the addon data for that kind of thing as it lets people create arbitrary characters in the database.

**Comment by R41z0r** [comment]
Amazing, worked like a charm, thanks :)

-- 
Philipp Michael Barth

Von: Freddie ***@***.***> ***@***.***>
Antworten: ThingEngineering/wowthing-again
***@***.***>
***@***.***>
Datum: 13. November 2021 at 08:34:52
An: ThingEngineering/wowthing-again ***@***.***>
***@***.***>
CC: R41z0r ***@***.***> ***@***.***>, Author
***@***.***> ***@***.***>
Betreff:  Re: [ThingEngineering/wowthing-again] Newly created characters
are missing (Issue #180)

Log out and back in is the easiest way, can only check the API for
