### ISSUE TITLE
Transmog incomplete/doubled 

### ISSUE THREAD

**Issue by R41z0r** [ThingEngineering/wowthing-again#181]
Hey there,

Maybe the first thing is just a visual bug on mobile
![54448C6C-09B6-4402-83D0-89A1EB051515](https://user-images.githubusercontent.com/6240199/141611013-074f1eb0-bb18-4172-968f-6e30729187f5.png)
You can see that the venthyr symbol is doubled above.

And the other thing, it's kinda wierd as I can only see the completely collected gear from leather by kyrian, but I already have venthyr, kyrian of cloth and necrolord of leather as well. Is there something I am missing? 
Thanks

**Comment by madcowfred** [comment]
Venthyr got 8 new sets for some reason (2 of everything) while everyone else got 4, no idea why. I should add something like `1` and `2` to them to differentiate.

Appearances have been a little weird lately - best bet is to log into characters with the transmog available, make sure you open the Appearances/Transmog window, wait for the WoWthing message about scanning 1234 items, and uploading the data file after logging out/reloading UI.

**Comment by R41z0r** [comment]
Nice to know, I'll try that. And the UI thing in the middle, you can see
that priest, dh and druid are on the same column, but that's the cloth one.
And plate/mail column hasn't a header because of that. Maybe mobile issue

-- 
Philipp Michael Barth

Von: Freddie ***@***.***> ***@***.***>
Antworten: ThingEngineering/wowthing-again
***@***.***>
***@***.***>
Datum: 13. November 2021 at 09:06:37
An: ThingEngineering/wowthing-again ***@***.***>
***@***.***>
CC: R41z0r ***@***.***> ***@***.***>, Author
***@***.***> ***@***.***>
Betreff:  Re: [ThingEngineering/wowthing-again] Transmog incomplete/doubled
(Issue #181)

Venthyr got 8 new sets for some reason (2 of everything) while everyone

**Comment by madcowfred** [comment]
I actually finally tracked down the weird column stuff, should be fixed now.
