### ISSUE TITLE
Legion Violet Hold

### ISSUE THREAD

**Issue by R41z0r** [ThingEngineering/wowthing-again#202]
Hey there, technically everything is right here, but from games perspective you can only kill 3/8 bosses.

Maybe you can change it to the bosses that were killed?
![52BD0DB3-DC5D-4383-BE38-9B474921D317](https://user-images.githubusercontent.com/6240199/143902726-bf073cee-cb91-4cfe-8f7e-72c0ff07e17a.png)

**Comment by madcowfred** [comment]
This should be added now
