### ISSUE TITLE
RFI - Reputations Page

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#21]
![image](https://user-images.githubusercontent.com/27977095/121765873-119da900-cb1c-11eb-8eee-7eb21ae7b10d.png)

- Lookin at reputations page, what I'd like to see here is a column highlight or hover text if you still need a major vendor or prestige item (toy, artifact skin, mount, first instance of a pet). Might be better to have a class page for artifact stuff and other similar things
- Definitely want to see hover text for faction names
- I could probably figure it out, but what do the colors indicate? Is white neutral? Is green friendly? So this character is 80% of the way through neutral? 
![image](https://user-images.githubusercontent.com/27977095/121765899-43af0b00-cb1c-11eb-8ec7-7c6732f7bb98.png)

**Comment by madcowfred** [comment]
Think this is all implemented now
