### ISSUE TITLE
"Highlight Missing Enchants" not working correctly

### ISSUE THREAD

**Issue by R41z0r** [ThingEngineering/wowthing-again#239]
Hey there, on some items the 'Highlight missing enchants' displays missing ones even if they have the best enchant on it:

![Bildschirmfoto 2021-12-23 um 13 15 02](https://user-images.githubusercontent.com/6240199/147239287-b4b03afe-fb67-48fd-836c-42af69a0041b.png)
You see here 'Soul Treads' (https://www.wowhead.com/spell=323609/soul-treads)
The character in picture is my resto shami so no need for Agi enchant.

It even reports stuff, when it is not 'the best level of enchant' like 10str instead of 15str - But this is not really 'missing enchant' better would be the term 'missing best enchant'.

**Comment by madcowfred** [comment]
It looks like your shaman is Enhance spec there so it's mad about the enchant not being Agility. The best level stuff is just an arbitrary "the good ones are cheap on _my_ realm" decision, I'll see about changing it to multiple "Missing enchant" and "Notbest enchant" options

**Comment by madcowfred** [comment]
Going to close this, achievements are all dirt cheap since the AH change
