### ISSUE TITLE
Sort Characters - Optional Sort Override or Pinning

### ISSUE THREAD

**Issue by justinryder** [ThingEngineering/wowthing-again#249]
On the sort characters page, I really like how you can pick which properties you want to sort by, but I'd also like a means of overriding that on a character by character basis so I can manually keep my commonly played characters at the top. Having an optional sort override or a pinning feature would allow for finer control over commonly played characters, while allowing the automatic grouping/sorting logic to handle the rest of your alts.

#/settings/sort-characters

e.g. I want to sort these characters as:
Kiarah (main, lower ilvl cause logged out as alt spec)
Aevyra (lower ilvl cause newest alt gearing focus)
Kaelish
Xelnathas
rest by ilvl > level > name

![image](https://user-images.githubusercontent.com/2396658/147537586-a1848383-39be-4b2e-9621-051230520ebc.png)

**Comment by madcowfred** [comment]
Added, check Settings -> Pin Characters for a very janky implementation.
