### ISSUE TITLE
Site not working anymore

### ISSUE THREAD

**Issue by R41z0r** [ThingEngineering/wowthing-again#259]
Hey there, I'm using Safari on Mac for 3 days now I'm not able to use the website, if I click on any other element there, the right screen stays black. On the javascript console I get:
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'n.querySelector("li a").getAttribute')

![Bildschirmfoto 2022-01-10 um 18 49 07](https://user-images.githubusercontent.com/6240199/148813921-914a137b-dfe7-4e2d-a002-2e05a17df1e8.png)

I already cleared my whole web information in Safari and tried it with private tab, it's not working here

![Bildschirmfoto 2022-01-10 um 18 51 09](https://user-images.githubusercontent.com/6240199/148814202-d28f1810-f781-448d-bb9d-214cc9f19a51.png)

**Comment by madcowfred** [comment]
Should be fixed now
