### ISSUE TITLE
Add souls to the vendor page for Night Fae

### ISSUE THREAD

**Issue by ninaarens** [ThingEngineering/wowthing-again#322]
![image](https://user-images.githubusercontent.com/8618272/161385574-5fa5babe-847c-49ff-8f89-016a431a784a.png)

These four souls have an anima cost, with those from Spindlenose also costing some grateful offerings. I'd expect to see them on the vendor page for Night Fae.

**Comment by madcowfred** [comment]
The problem with souls is that they're character specific, and implementing something along the lines of "I only want these on character Steve" is a problem in several other areas (eg Zone Maps). I have no real useful ideas for how to handle that 😞

**Comment by ninaarens** [comment]
> I have no real useful ideas for how to handle that 😞
Well, you could go the ATT route and have account-wide tracking? Or a hybrid mode where you show if another character has something but this character still lacks it? Let the logged in use switch between the 3 modes (character, hybrid, account).
