### ISSUE TITLE
Synology

### ISSUE THREAD

**Issue by Zarctus** [ThingEngineering/wowthing-again#327]
hey !
Love your work, but, i want to know if it's possible to run it on a synology nas with docker, and how to install it.

Great job.

**Comment by madcowfred** [comment]
It should be possible, but I have no access to a Synology device to give any specific instructions. If the steps in https://github.com/ThingEngineering/wowthing-again#local-setup don't help then please open a new issue with specific problems. #414 probably covers some common issues that will crop up :(
