### ISSUE TITLE
Add Mechanized chest to Mechagon zone map page

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#347]
Required for Most Minis Wins meta

**Comment by kyatastrophe** [comment]
QUEST ID is in a comment https://www.wowhead.com/object=325664/mechanized-chest#comments

**Comment by kyatastrophe** [comment]
You have the chest icon you're using it in the Argus maps

**Comment by madcowfred** [comment]
Added
