### ISSUE TITLE
Add instructions for making the sync client start on PC start

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#354]
Select the Start  button and scroll to find the app you want to run at startup.

Right-click the app, select More, and then select Open file location. This opens the location where the shortcut to the app is saved. If there isn't an option for Open file location, it means the app can't run at startup.

With the file location open, press the Windows logo key  + R, type shell:startup, then select OK. This opens the Startup folder.

Copy and paste the shortcut to the app from the file location to the Startup folder.

**Comment by madcowfred** [comment]
Added a setting for this in v0.6.0
