### ISSUE TITLE
Dalaran Hearthstone Tracking

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#368]
https://www.wowhead.com/quest=40519/legion-the-legion-returns

https://www.wowhead.com/quest=43926/legion-the-legion-returns

**Comment by rypakal** [comment]
https://www.wowhead.com/quest=44184/in-the-blink-of-an-eye this appears to be the raid skip versions
https://www.wowhead.com/quest=44663/in-the-blink-of-an-eye this is the non skip version

both are marked complete on all of my alts that have it

**Comment by madcowfred** [comment]
Added to Progress under Travel
