### ISSUE TITLE
Fix completion to achievement output

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#408]
![image](https://user-images.githubusercontent.com/27977095/174008543-a5676016-c056-4177-8ae5-fa2d023a05df.png)
![image](https://user-images.githubusercontent.com/27977095/174008555-51dc7698-4eb5-488c-9721-a76b52a3f76b.png)

**Comment by madcowfred** [comment]
Fixed. Mixing Monstrosities requires addon >= 9.2.5.6
