### ISSUE TITLE
Mechagon chest completion not tracking properly

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#411]
Completed on Kyantstop at 3:05am Eastern - uploaded, does not reflect

**Comment by kyatastrophe** [comment]
I suspect it's looking for completion of unlock and only checking those characters, but all characters can loot the chest

**Comment by madcowfred** [comment]
This should be fixed now with addon update:
- there's 2 separate tracking quests (reclamation rig/chest) and I was only checking for the rig one
- minimum level for zone has been dropped to 10 which should be close enough
