### ISSUE TITLE
Attempted fetch breaks while offline

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#420]
![image](https://user-images.githubusercontent.com/27977095/174671923-bf01c511-7190-4023-9172-2e89ec92f5f1.png)
![image](https://user-images.githubusercontent.com/27977095/174671927-b3b798c7-603e-4304-a3f2-9ecb8dac1d1a.png)

PC went to sleep, when fetch failed it went KABOOM

**Comment by madcowfred** [comment]
Should be fixed now, as long as the first fetch succeeds future refreshes won't break everything
