### ISSUE TITLE
'Expedition Leader' achievement display

### ISSUE THREAD

**Issue by Silly26** [ThingEngineering/wowthing-again#424]
When viewing the 'Expedition Leader' achievement (Achievements -> Expansion Features -> Island Expeditions), some of the criteria is missing:

![Expedition_Leader](https://user-images.githubusercontent.com/8854060/174773732-1ba0b6c0-fd53-4018-94c8-b569b6ae3439.png)

**Comment by madcowfred** [comment]
Achievements are under construction, mostly because I don't want to deal with fixing the weirdness that is criteria data. I'll leave this open but it's a pretty low priority to look at because it sucks.

**Comment by madcowfred** [comment]
This is, well, kinda fixed now but good enough
