### ISSUE TITLE
Progress Additions!

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#437]
Legion - Legionfall campaign
Shadowlands - Pet synthesis, Mount synthesis
WoD - Music Rolls

**Comment by kyatastrophe** [comment]
Pet Protoform Synthesis is locked behind Quest ID 65419 (called Protoform Synthesis)
Mount Protoform Synthesis is locked behind Quest ID 65427 (called A New Architect)

Garrison Music Rolls are locked behind Quest ID 38356 (Alliance) or Quest ID 37961 (Horde), both called Bringing the Bass.

**Comment by madcowfred** [comment]
Added
