### ISSUE TITLE
Vendors page

### ISSUE THREAD

**Issue by Qwagsoir** [ThingEngineering/wowthing-again#466]
DMF vendors and PvP set vendors would probably fit in relatively well on there

**Comment by madcowfred** [comment]
The sticking point with PvP vendors in general is that they tend to have many, _many_ items. With vendor data also being used on Zone Maps, this would probably break tooltips - not sure how to deal with that.

**Comment by Qwagsoir** [comment]
Would it be possible to not add them to zone maps, or perhaps a dummy that takes you to the vendor page?

**Comment by madcowfred** [comment]
Added a bunch of these, it's tedious but shouldn't take long to finish up
