### ISSUE TITLE
Trial of Crusader Set Bug

### ISSUE THREAD

**Issue by Lucetia** [ThingEngineering/wowthing-again#468]
A friend and I were comparing our raid set data and I noticed something odd.

Here it shows for instance on my warlock I am 3/8: 

![image](https://user-images.githubusercontent.com/36181235/177961107-cd57a12f-4b35-4b3e-91b0-a4a3aa5c873b.png)

But if I go to my set appearances on my alliance toon it shows I am actually 7/8 (I am missing the waist).

![image](https://user-images.githubusercontent.com/36181235/177961208-be547967-37fd-42d1-8a08-11f77d0b1dbb.png)

My friend is in a similar boat and he collects only shared appearances (so anything that shares counts it) whereas I do the completionist method where I grab every single itemID. Both of us are showing the same thing.  For some reason it is ignoring the actual items I own from the alliance set.  This happens on the rogue set as well.  

I've tried reuploading the file (even after WoW was closed) and waited a day (well a few weeks) and refreshed the file and the same effect still occurs.

**Comment by madcowfred** [comment]
How very strange. Can you try updating to addon v9.2.5.10 and logging in/out on your alliance warlock?
