### ISSUE TITLE
Mouseover text displaying duplicate information

### ISSUE THREAD

**Issue by Silly26** [ThingEngineering/wowthing-again#471]
![image](https://user-images.githubusercontent.com/8854060/178139761-f561b60d-582c-4f8f-b00b-368d6bb9014f.png)
![image](https://user-images.githubusercontent.com/8854060/178139745-e4ff9e0a-2a82-4a87-9cc2-ab107f9d691c.png)

When mousing over the icons to the left of the character name (seemingly on any page -- tested on Currencies and Home), I'm getting the above display. I'm assuming the vertical bar `|` is supposed to be to the left or not present, and the classes are duplicated.

**Comment by madcowfred** [comment]
Oops, this is a side effect of how I store male/female names for things (doesn't matter for English, does for some other languages).

**Comment by madcowfred** [comment]
Fixed
