### ISSUE TITLE
Reputation grid only shows Horde reputations for a mixed roster of characters

### ISSUE THREAD

**Issue by ninaarens** [ThingEngineering/wowthing-again#474]
I first noticed this issue on the pandaria reputation page, it lists the Sunreaver Onslaught, but not the Kirin Tor Offensive on the grid. Same for Operation: Shieldwall, it is missing while Dominance Offensive is showing. This seems to be the case for the other expansions that have equivalent reputations (one for each faction) as well. I have a mixed roster of alliance and horde characters so I would expect to see a column for each when all characters are showing on the grid.

![image](https://user-images.githubusercontent.com/8618272/178587885-23432ff7-5f88-4a51-ab29-c6cc3f2c0163.png)

**Comment by madcowfred** [comment]
WoWthing has always had support for split faction reputations, I just kinda managed to completely break it with some bad copypasta. Fixed now.
