### ISSUE TITLE
Garrison page

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#527]
> Critty (Druid Comp) — Today at 6:21 PM
> is there a current feature to see garrison buildings and upgrades?
> only reason i ask is mr emerno and im sure others need saurfang from r3 garrison and id like a quick way to check out what toons have that, and im sure it would be good to see what other buildings we have or something

**Comment by madcowfred** [comment]
Added a basic version in Progress>Warlords of Draenor>Garrison Buildings
