### ISSUE TITLE
Anonymize character/realm names doesn't hide names on Mythic+ highest keys for dungeon.

### ISSUE THREAD

**Issue by redluxx** [ThingEngineering/wowthing-again#56]
- Public Profile 
- Anonymize character/realm names enabled

Having a public profile and the anonymize option selected hides the char & server names throughout the webapp. However on the Mythic+ tab, hovering over your highest key completed shows character names. Thus removing the anonymize factor as it can be easily matched to the char your looking at.

![names being shown](https://user-images.githubusercontent.com/39776429/124517102-07995e00-dddb-11eb-8cc3-ff486601337a.jpg)

**Comment by madcowfred** [comment]
Thank you for the bug report! A fix for this will be going out in about 5 minutes.
