### ISSUE TITLE
Profession Skill List

### ISSUE THREAD

**Issue by Amethice** [ThingEngineering/wowthing-again#565]
Simple grid view - go to, for example, the Leatherworking page. Rows are characters (filtered for only those who have Leatherworking as one of their professions). Columns are each expansion's profession tier, with the skill level (colour coded for the various maximums).

Use case: It can be useful for a quick overview of where to send skillup materials. Say I have a bunch of copper ore, I can go to my Mining page and see if there's anyone with a low enough Vanilla Mining skill that smelting it would actually skill them up.
Or, I might need some Draenor leathers. Now, collecting leather is easy, but a quick glance at my Skinning page will tell me if I can double up this task with some skillups by picking a skinner who hasn't maxed their Draenor skill yet.

Note
- Cooking Ways for Pandaria Cooking should preferably be included in the Cooking view, especially since those aren't available in the Web API (until they fix it, hopefully before the heat death of the universe), so without the addon gathering the data it's a pain to keep track of.
- Show specializations for Alchemists and Engineers.

Bonus things (can easily be moved to a later improvement ticket)
- If possible, track which characters still need Draenor Research Token recipes and other discovery recipes that are on a daily cooldown, so it's easy at a glance to see who needs daily logons for their cooldowns (draenor Secrets recipes for all crafting proffessions, Inscription ink research (glyph discovery), Pandaria discovery recipes (lightning steel, balanced trillium, imperial silk, celestial cloth, magnificence of leather/scales, hardened magnificent hide, northrend jewelcrafter and alchemy research, etc).
- Another super bonus thing: for Alchemists, see who is on their Transmutation lockout.

**Comment by madcowfred** [comment]
This is mostly added at this point, under 🚧 Professions on the main page and many recipes are under Characters>Steve>Professions. Ways are not yet since they're weird, and daily lockouts are also weird. Some progress though.
