### ISSUE TITLE
UI Issue while using WowThing Collector

### ISSUE THREAD

**Issue by R41z0r** [ThingEngineering/wowthing-again#589]
Hey there, for a longer time now, I have an issue with my Bag UI while using WowThing Collector.
I noticed some time ago, that when I open my Bags for the first time after either reload or a loading screen, my bag is totally scrubbed.

I use AdiBags as my bag addon and that's the way it looks like, when using wowthing collector:
![Bildschirmfoto 2022-08-29 um 08 39 14](https://user-images.githubusercontent.com/6240199/187139120-ef659a04-7047-49f0-ad1f-ca898111b8df.png)
If I close and open bag after that appereance, the "bug" is away for this time, but after a reload/world load the bug is back up again.
Normally the bags should look like this:
![Bildschirmfoto 2022-08-29 um 08 39 45](https://user-images.githubusercontent.com/6240199/187139213-aff7b8b7-fd13-4e89-bf49-26689b350a92.png)

I disabled all my addons and just left WowThing Collector and AdiBags up and thats the result you can see above.

**Comment by madcowfred** [comment]
Yeah, I've run into this but haven't been able to track down what's causing it yet. Something very weird, apparently.

**Comment by R41z0r** [comment]
'Not for me unfortunately, when I let wowcollector disabled, i can't reproduce the issue :/
Maybe because both addons use the same hooks and that's a problem for him?

**Comment by R41z0r** [comment]
Hey again, I started to track down your code and found something, maybe it's easy to fix that for you:
Codeline 1279: 
`local` sources = C_TransmogCollection_GetAppearanceSources(visualId, categoryID, transmogLocation)`
When I change that line to an empty map like:
`local sources = {}`
All is working fine, is there maybe something with the API-Call to: C_TransmogCollection_GetAppearanceSources with the visualId? Because you used the one with two arguments before and no UI bug happend but after that line with three arguments, it's bugging.

I also tried to comment all things in the following for loop out to see, if it's really the api call but still, with an empty for loop the error exists as well so it has to be that line where you call GetAppearanceSources with three Arguments.

Don't get me wrong, it could also be a problem with adibags for sure, I just want to inform you of that.

**Comment by Cidan** [comment]
Hi there.

AdiBags maintainer here. The actual bug is AdiBags#629 -- this happens because the Blizzard API asynchronously loads data for items in bags. This is on our list to fix as soon as we do some new layout work. Feel free to track this bug for a fix.

Thanks!

**Comment by madcowfred** [comment]
> Hi there.
> 
> AdiBags maintainer here. The actual bug is AdiBags#629 -- this happens because the Blizzard API asynchronously loads data for items in bags. This is on our list to fix as soon as we do some new layout work. Feel free to track this bug for a fix.
> 
> Thanks!

Oh, awesome, thanks for the info. I looked through the AdiBags issues and nothing jumped out at me as being this weird layout thing
