### ISSUE TITLE
[Suggestion] Tracking fated raid bosses defeated progress / Dinar earned/spent

### ISSUE THREAD

**Issue by strchsr** [ThingEngineering/wowthing-again#591]
An option to track progress on Crossing Fate/Turning the Wheel and a way to determine how many Dinar a character has in their possession or has spent.

**Comment by madcowfred** [comment]
Progress>Shadowlands>Fated tracks the 3 quests, can probably add some way to show how many you have right now

**Comment by Qwagsoir** [comment]
The Items function can look for Dinars currently in your posession, though you'd have to do the math to see how many you spent

**Comment by madcowfred** [comment]
Luckily this isn't relevant any more!
