### ISSUE TITLE
Legion Toys incorrectly listed under WoD

### ISSUE THREAD

**Issue by alphabitnz** [ThingEngineering/wowthing-again#609]
The following toys are all obtained from Legion content, but are mistakenly listed in the Toys>Warlords of Draenor category

- Golden Hearthstone Card: Lord Jarraxus
- Brulfist Idol
- Lingering Wyrmtongue Essence
- Mote of Light
- Prismatic Bauble
- The "Devilsaur" Lunchbox

**Comment by madcowfred** [comment]
This should all be fixed now
