### ISSUE TITLE
Add sorts on various pages

### ISSUE THREAD

**Issue by kyatastrophe** [ThingEngineering/wowthing-again#619]
In addition to quicksort options it would be nice to be able to 
1) revert to homepage sort style
2) sort by other shit like armor type

**Comment by Sahasrahla** [comment]
My use-case for this feature would be sorting by Rested XP on the Home page so I know at a glance which characters are most ready to spam more Timewalking dungeons. I can sort each Group table by some other columns (Gold, and iLvl in particular) but not others (Rested XP and Hearthstone Location).

**Comment by madcowfred** [comment]
Added rested xp/current location/hearth location sorting, going to count this one as "close enough" for now with the character filter + Home sorting
