### ISSUE TITLE
Selection Menu on Journal Mog Page

### ISSUE THREAD

**Issue by toixd** [ThingEngineering/wowthing-again#669]
Hello,

on the side the selection menu it showing two times Classic - Shadowlands.
Darkmaul Citadel is 3 times on the selection menu. it seems that something is duplicated.

I have added a picture to explain it better

![unknown](https://user-images.githubusercontent.com/20703290/194850786-c1974529-b727-4451-b0e1-0fe61d3510a5.png)

**Comment by madcowfred** [comment]
Uhhh, that's weird. It should fix if you reload the page, but if you can work out how to make it break like this I can track down what might be causing it.

**Comment by toixd** [comment]
I tried with the relog, no changes, the menu remains so double and triple. 
I have now tried it with the browser Opera, there it works and is not double and everything works fine. 
If I try it with Firefox it appears again. I have deleted the cache. 

Maybe it is a browser problem?
I have my settings Puplic on, vllt it helps to find out what the problem is: https://wowthing.org/user/Elnor

**Comment by madcowfred** [comment]
Fixed now. Two separate issues:

- The extra "Miscellaneous" tier was being added once every time through the languages. `deDE` is language #3 so it had 3 - `itIT` had 8 😓
- The Raids>Shadowlands>Shadowlands is a side-effect of how Blizzard names world boss categories. I should probably just rename those to "World Bosses" to reduce confusion
