### ISSUE TITLE
ingame icon question & data tool

### ISSUE THREAD

**Issue by bonesoul** [ThingEngineering/wowthing-again#863]
So I'm trying to get some understanding on the repo for future contributions.

Here is my question

Reputation icons (https://github.com/ThingEngineering/wowthing-again/blob/dd99d856dde45a0cd3197484a0dc856f4eee3032/apps/frontend/components/reputations/ReputationsTableHead.svelte) seem to use (https://github.com/ThingEngineering/wowthing-again/blob/dd99d856dde45a0cd3197484a0dc856f4eee3032/apps/frontend/components/images/sources/WowthingImage.svelte)

which is an actually

`
<Image
    src="https://img.wowthing.org/{size}/{name}.webp"
    alt={name}
    size={actualSize}
    {cls}
    {lazy}
    {tooltip}
/>`

So it seems to be served over https://img.wowthing.org/40/achievement/16529.webp

I'm trying to locate the icons location through the repository but couldn't find it. Can you guide me?

One more question, is there a tool that updates data files like https://github.com/ThingEngineering/wowthing-again/blob/main/data/reputations/09_dragonflight.yml

**Comment by madcowfred** [comment]
> So I'm trying to get some understanding on the repo for future contributions.
> 
> I'm trying to locate the icons location through the repository but couldn't find it. Can you guide me?

Icons are generated by a hot mess of scripts in the `wowthing-media` repository. I haven't been keeping it up to date, but it basically takes raw BLP exports from the game client + DBC dumps and generates hundreds of thousands of images which I then manually upload.

> One more question, is there a tool that updates data files like https://github.com/ThingEngineering/wowthing-again/blob/main/data/reputations/09_dragonflight.yml

Most data files are purely manually edited with a few exceptions (transmog sets and vendors have tools to help). Some manual data is still hardcoded in various places, but I'm gradually moving as much as possible to be data-driven instead.

**Comment by bonesoul** [comment]
well then wowthing-media isn't an open source repo i guess?

**Comment by madcowfred** [comment]
Apparently I never ported it over from [GitLab](https://gitlab.com/thing-engineering/wowthing/wowthing-media), https://github.com/ThingEngineering/wowthing-media exists now and is up to date
