### ISSUE TITLE
Toys out of date

### ISSUE THREAD

**Issue by Roxatha** [ThingEngineering/wowthing-again#949]
Hi, since 3 days, i have notice that even with sync manualy, the Action space for toys is showing either 0% or the usual % but when u enter it shows up toys that i already have.
The 1st pic is how it shows up today at 21.42hr Canary island time
The send is to prove i own the toy that is show as non owned.

![ff7ebf12b98de783623b6326649b429d](https://github.com/ThingEngineering/wowthing-again/assets/17516158/ed2cee62-7ef7-45c3-ae3d-350570dcd8dd)
![18d23fa6d54c7a9a3df43b8abcb3b3d2](https://github.com/ThingEngineering/wowthing-again/assets/17516158/83669e2c-337c-438b-a789-484f2e59b787)

**Comment by madcowfred** [comment]
This should be fixed now
