### ISSUE TITLE
Profession Cooldowns

### ISSUE THREAD

**Issue by SethForrest** [ThingEngineering/wowthing-again#966]
It would be great to be able to track profession cooldowns per character. 

All my alts have Tailoring and Alch for the crafting cooldowns. I track them with Altohaulic now, but you have to be logged in to check that. It would be wonderful if Thing could track them like it does for rested XP

**Comment by madcowfred** [comment]
This was added a while back, Settings>Layout has "Profession Cooldowns" for work orders and profession-specific cooldowns (eg transmutes).
