### ISSUE TITLE
Track unlocked raid skips across all characters

### ISSUE THREAD

**Issue by aurell1** [ThingEngineering/wowthing-again#967]
I think it would be nice if we could keep track of which characters, in our army of alts, have certain skips unlocked. 

For example which one has completed https://www.wowhead.com/quest=37031/sigil-of-the-black-hand-mythic to be able to go straight to the last boss in Blackrock Foundry, or https://www.wowhead.com/quest=49135/antorus-the-burning-throne-the-heart-of-argus for Antorus. 

There's a great number of such quests, and it'd be a huge help to the user to be able to easily keep track which character has it done.

**Comment by madcowfred** [comment]
This already exists, just the usual "finding stuff is pretty hard you know" problem :( https://freddie.wowthing.org/#/progress/raid-skips
