### ISSUE TITLE
Bug: Profession weeklies list shows 45 skill for craft quest, but you need 50?

### ISSUE THREAD

**Issue by drnoonien** [ThingEngineering/wowthing-again#975]
Noticed a bug related to the enchanting craft weekly, it says it's locked behind 45 skill, but in-game I had to level to 50 to unlock it. Unsure if it's the same for all profs or just enchanting, didn't find any info online.

![](https://i.imgur.com/b9gjizj.png)

**Comment by drnoonien** [comment]
Closing this, unsure if I actually got it right and don't want to send anyone on a goose chase.

**Comment by madcowfred** [comment]
Oh, I meant to reply to this and forgot. It's actually different per profession (or maybe even per weekly?) and I didn't have the energy to track down exactly which ones are 45 vs 50 😬
